name: CIC Technology
favicon: null
layout_spectrum: 0.2650361268315464
typography_spectrum: 0.30048095947131515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#666666'
    - '#008494'
    - '#ca3100'
    - '#b2b2b2'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.2350972096901387
  rhythmicContrast: 0
purpose: []
